vm_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('fleet_management.urls'))
]

fleet_management/models.py
import datetime
from django.db import models
from django.conf import settings


class Vehicle(models.Model):
    CATEGORY_CHOICES = (
        ('L', 'Light'),
        ('H', 'Heavy')
    )

    number = models.CharField(max_length=127, unique=True)
    model        = models.CharField(max_length=127)
    joining_date = models.DateField(auto_now_add=True)
    capacity     = models.PositiveIntegerField()
    category     = models.CharField(max_length=1, choices=CATEGORY_CHOICES)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.number



class VehicleCondition(models.Model):
    vehicle = models.ForeignKey(Vehicle,
                                on_delete=models.CASCADE,
                                unique_for_date='date',
                                related_name='conditions')

    is_ok = models.BooleanField(default=True)
    date = models.DateField(default=datetime.date.today)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.vehicle.number


class Route(models.Model):
    CATEGORY_CHOICES = (
        ('L', 'Long Distance'),
        ('S', 'Short Distance')
    )

    name           = models.CharField(max_length=127, unique=True)
    category       = models.CharField(max_length=1, choices=CATEGORY_CHOICES)
    branch_manager = models.OneToOneField(settings.AUTH_USER_MODEL,
                                          on_delete=models.SET_NULL,
                                          null=True,
                                          related_name='route',
                                          limit_choices_to={"groups__name": "Branch Manager"})

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class Trip(models.Model):
    vehicle     = models.ForeignKey(Vehicle, on_delete=models.CASCADE, related_name='trips')
    origin      = models.ForeignKey(Route, on_delete=models.CASCADE, related_name='outgoing_trips')
    destination = models.ForeignKey(Route, on_delete=models.CASCADE, related_name='incoming_trips')
    via         = models.ManyToManyField(Route, blank=True)

    driver      = models.ForeignKey(settings.AUTH_USER_MODEL,
                                    on_delete=models.SET_NULL,
                                    null=True,
                                    limit_choices_to={"groups__name": "Driver"}
                                    )

    date = models.DateField(default=datetime.date.today)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    @property
    def via_list(self):
        return ', '.join([v.name for v in self.via.all()])


    def __str__(self):
        return "vehicle no: {}, from:{} to:{}, driver: {}.".format(self.vehicle, self.origin.name, self.destination.name, self.driver.name)


class VehicleInOutInfo(models.Model):
    trip = models.ForeignKey(Trip, on_delete=models.CASCADE, related_name='trip_info')
    route = models.ForeignKey(Route, on_delete=models.CASCADE, related_name='route_info')
    is_arrived = models.BooleanField(default=False)
    is_leaved = models.BooleanField(default=False)
    arrived_at = models.DateTimeField(null=True, blank=True)
    leaved_at = models.DateTimeField(null=True, blank=True)

    date = models.DateField(default=datetime.date.today)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "vehicle no: '{}' trip id: {}, route: {}".format(self.trip.vehicle, self.trip.id, self.route.name)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %}Fleet Management{% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    {% block css %}
    {% endblock %}

</head>
<body>
<div class="container">
    {% include 'header.html' %}


    <form class="form-inline text-right">
        <div class="form-group mx-sm-3 mb-2">
            <input name="date" type="text" data-toggle="datepicker" class="form-control" id="inputPassword2" value="{{ date }}">
        </div>
        <button type="submit" class="btn btn-default mb-2">Go to Date</button>
    </form>


    <hr>

    {% block content %}
    {% endblock %}

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
            integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
            crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
            crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fengyuanchen/datepicker@0.6.4/dist/datepicker.css">
    <script src="https://cdn.jsdelivr.net/npm/@fengyuanchen/datepicker@0.6.4/dist/datepicker.js"></script>

    {% block javascript %}
        <script>
            $('[data-toggle="datepicker"]').datepicker({
                format: 'yyyy-mm-dd',
                weekStart: '6'
            });
        </script>
    {% endblock %}
</div>
</body>
</html>

templates/header.html
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Fleet Management</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                {% if perms.fleet_management.add_vehiclecondition %}
                    <li><a href="{% url 'vehicle_condition' %}">Vehicle Conditions</a></li>
                    <li><a href="{% url 'set_vehicle_condition' %}">Set Vehicle Condition</a></li>
                {% endif %}
                {% if perms.fleet_management.add_trip %}
                    <li><a href="{% url 'available_vehicles' %}">Available Vehicles and Trips</a></li>
                    <li><a href="{% url 'set_trip' %}">Set Trip</a></li>
                {% endif %}
                {% if perms.fleet_management.add_vehicleinoutinfo %}
                    <li><a href="{% url 'vehicle_info' %}">Set Vehicle In/Out Info</a></li>
                {% endif %}
            </ul>

            <ul class="nav navbar-nav navbar-right">
                {% if request.user.is_authenticated %}
                    <li><a href="{% url 'logout' %}?next={{ request.path|urlencode }}">Logout</a></li>
                {% else %}
                    <li><a href="{% url 'login' %}?next={{ request.path|urlencode }}">Login</a></li>
                {% endif %}
            </ul>
        </div><!--/.nav-collapse -->
    </div><!--/.container-fluid -->
</nav>

{#messages#}
{% for message in messages %}
    <div class="alert {{ message.tags }} alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        {{ message }}
    </div>
{% endfor %}